#
# Copyright (c) 2020 ARM Limited
#
# SPDX-License-Identifier: Apache-2.0

ARG IMAGE_REGISTRY=docker.io
#ubuntu: docker image to be used to create a rootfs
#@OS_VERSION@: Docker image version to build this dockerfile
FROM ${IMAGE_REGISTRY}/ubuntu:@OS_VERSION@

# This dockerfile needs to provide all the componets need to build a rootfs
# Install any package need to create a rootfs (package manager, extra tools)

# Avoid tzdata setup
ENV DEBIAN_FRONTEND noninteractive

# RUN commands
RUN apt-get update && apt-get install -y \
    autoconf \
    automake \
    binutils \
    build-essential \
    chrony \
    coreutils \
    curl \
    debianutils \
    debootstrap \
    g++ \
    gcc \
    git \
    golang-go \
    libdevmapper-dev \
    libc6-dev \
    libgpgme-dev \
    libssl-dev \
    libstdc++-8-dev \
    m4 \
    make \
    pkg-config \
    sed \
    systemd \
    tar \
    vim
# This will install the proper packages to build Kata components
@INSTALL_MUSL@
@INSTALL_RUST@
