# Copyright (c) 2025 Microsoft Corporation
#
# SPDX-License-Identifier: Apache-2.0
FROM alpine:3.22.1

RUN apk add --no-cache \
    openvpn \
    easy-rsa \
    openssl \
    net-tools \
    iproute2

CMD ["/bin/sh"]
