# Landlock LSM support:
# Unprivileged access-sandboxing mechanism that allows processes
# to restrict themselves (and their future children) by defining
# fine-grained filesystem, network, and scoping rules.

CONFIG_SECURITY_LANDLOCK=y
