// This file is generated by ttrpc-compiler 0.6.1. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clipto_camel_casepy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct HypervisorClient {
    client: ::ttrpc::r#async::Client,
}

impl HypervisorClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        HypervisorClient {
            client: client,
        }
    }

    pub async fn create_vm(&self, ctx: ttrpc::context::Context, req: &super::hypervisor::CreateVMRequest) -> ::ttrpc::Result<super::hypervisor::CreateVMResponse> {
        let mut cres = super::hypervisor::CreateVMResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "hypervisor.Hypervisor", "CreateVM", cres);
    }

    pub async fn start_vm(&self, ctx: ttrpc::context::Context, req: &super::hypervisor::StartVMRequest) -> ::ttrpc::Result<super::hypervisor::StartVMResponse> {
        let mut cres = super::hypervisor::StartVMResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "hypervisor.Hypervisor", "StartVM", cres);
    }

    pub async fn stop_vm(&self, ctx: ttrpc::context::Context, req: &super::hypervisor::StopVMRequest) -> ::ttrpc::Result<super::hypervisor::StopVMResponse> {
        let mut cres = super::hypervisor::StopVMResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "hypervisor.Hypervisor", "StopVM", cres);
    }

    pub async fn version(&self, ctx: ttrpc::context::Context, req: &super::hypervisor::VersionRequest) -> ::ttrpc::Result<super::hypervisor::VersionResponse> {
        let mut cres = super::hypervisor::VersionResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "hypervisor.Hypervisor", "Version", cres);
    }
}

struct CreateVmMethod {
    service: Arc<Box<dyn Hypervisor + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CreateVmMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, hypervisor, CreateVMRequest, create_vm);
    }
}

struct StartVmMethod {
    service: Arc<Box<dyn Hypervisor + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for StartVmMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, hypervisor, StartVMRequest, start_vm);
    }
}

struct StopVmMethod {
    service: Arc<Box<dyn Hypervisor + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for StopVmMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, hypervisor, StopVMRequest, stop_vm);
    }
}

struct VersionMethod {
    service: Arc<Box<dyn Hypervisor + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for VersionMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, hypervisor, VersionRequest, version);
    }
}

#[async_trait]
pub trait Hypervisor: Sync {
    async fn create_vm(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::hypervisor::CreateVMRequest) -> ::ttrpc::Result<super::hypervisor::CreateVMResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/hypervisor.Hypervisor/CreateVM is not supported".to_string())))
    }
    async fn start_vm(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::hypervisor::StartVMRequest) -> ::ttrpc::Result<super::hypervisor::StartVMResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/hypervisor.Hypervisor/StartVM is not supported".to_string())))
    }
    async fn stop_vm(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::hypervisor::StopVMRequest) -> ::ttrpc::Result<super::hypervisor::StopVMResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/hypervisor.Hypervisor/StopVM is not supported".to_string())))
    }
    async fn version(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::hypervisor::VersionRequest) -> ::ttrpc::Result<super::hypervisor::VersionResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/hypervisor.Hypervisor/Version is not supported".to_string())))
    }
}

pub fn create_hypervisor(service: Arc<Box<dyn Hypervisor + Send + Sync>>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("CreateVM".to_string(),
                    Box::new(CreateVmMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("StartVM".to_string(),
                    Box::new(StartVmMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("StopVM".to_string(),
                    Box::new(StopVmMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Version".to_string(),
                    Box::new(VersionMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("hypervisor.Hypervisor".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
