include: https://gitlab-templates.ddbuild.io/compute-delivery/v3/compute-delivery.yml

variables:
  CI_IMAGE: 3
  KERNEL_VERSION: 6.8
  KUBERNETES_CPU_REQUEST: "10"
  KUBERNETES_MEMORY_REQUEST: "20Gi"
  KUBERNETES_MEMORY_LIMIT: "40Gi"
  KERNEL_DEBUG_ENABLED: "yes"
  KERNEL_DATADOG_ENABLED: "yes"

stages:
  - ci-image
  - build
  - publish
  - notify

ci-image:
  stage: ci-image
  extends: .build-docker-image
  when: manual
  only:
    - branches
  variables:
    IMAGE_NAME: "$CI_PROJECT_NAME/ci"
    IMAGE_TAG: $CI_IMAGE
    CONTEXT_DIR: "./tools/packaging/kernel"
    TARGET: "build"

build-kernel-amd64:
  image: registry.ddbuild.io/$CI_PROJECT_NAME/ci:$CI_IMAGE
  stage: build
  tags: [ "arch:amd64" ]
  script:
    - cd tools/packaging/kernel
    - ./build-kernel.sh -v $KERNEL_VERSION setup
    - ./build-kernel.sh -v $KERNEL_VERSION build
    - cp kata-linux-*/arch/x86_64/boot/bzImage ./vmlinux-amd64
  artifacts:
    paths:
      - tools/packaging/kernel/vmlinux-amd64
    expire_in: 1 week

build-kernel-arm64:
  image: registry.ddbuild.io/$CI_PROJECT_NAME/ci:$CI_IMAGE
  stage: build
  tags: [ "arch:arm64" ]
  script:
    - cd tools/packaging/kernel
    - ./build-kernel.sh -v $KERNEL_VERSION setup
    - ./build-kernel.sh -v $KERNEL_VERSION build
    - cp kata-linux-*/arch/arm64/boot/Image.gz ./vmlinux-arm64
  artifacts:
    paths:
      - tools/packaging/kernel/vmlinux-arm64
    expire_in: 1 week

build-shim-amd64:
  image: registry.ddbuild.io/images/mirror/library/golang:1.24.5
  stage: build
  tags: [ "arch:amd64" ]
  variables:
    GOTOOLCHAIN: auto
  script:
    - cd src/runtime
    - make containerd-shim-v2
    - mv containerd-shim-kata-v2 containerd-shim-kata-v2-amd64
  artifacts:
    paths:
      - src/runtime/containerd-shim-kata-v2-amd64
    expire_in: 1 week

build-shim-arm64:
  image: registry.ddbuild.io/images/mirror/library/golang:1.24.5
  stage: build
  tags: [ "arch:arm64" ]
  variables:
    GOTOOLCHAIN: auto
  script:
    - cd src/runtime
    - make containerd-shim-v2
    - mv containerd-shim-kata-v2 containerd-shim-kata-v2-arm64
  artifacts:
    paths:
      - src/runtime/containerd-shim-kata-v2-arm64
    expire_in: 1 week

build-shim-rust-amd64:
  image: registry.ddbuild.io/images/mirror/rust:1.91
  stage: build
  tags: [ "arch:amd64" ]
  script:
    - apt-get update -q && apt-get install -yq musl-tools g++ cmake
    - INSTALL_IN_GOPATH=false ci/install_yq.sh
    - tests/install_rust.sh
    - cd src/runtime-rs
    - make clean-generated-files
    - make check
    - make PREFIX=/opt/kata QEMUCMD=qemu-system-x86_64
    - cp ../../target/x86_64-unknown-linux-musl/release/containerd-shim-kata-v2 containerd-shim-kata-v2-rust-amd64
  artifacts:
    paths:
      - src/runtime-rs/containerd-shim-kata-v2-rust-amd64
    expire_in: 1 week

build-shim-rust-arm64:
  image: registry.ddbuild.io/images/mirror/rust:1.91
  stage: build
  tags: [ "arch:arm64" ]
  script:
    - apt-get update -q && apt-get install -yq musl-tools g++ cmake
    - INSTALL_IN_GOPATH=false ci/install_yq.sh
    - tests/install_rust.sh
    - cd src/runtime-rs
    - make clean-generated-files
    - make check
    - ARCH=aarch64 make PREFIX=/opt/kata QEMUCMD=qemu-system-aarch64
    - cp ../../target/aarch64-unknown-linux-musl/release/containerd-shim-kata-v2 containerd-shim-kata-v2-rust-arm64
  artifacts:
    paths:
      - src/runtime-rs/containerd-shim-kata-v2-rust-arm64
    expire_in: 1 week

publish-artifacts:
  image: registry.ddbuild.io/$CI_PROJECT_NAME/ci:$CI_IMAGE
  stage: publish
  only:
    - tags
  tags: [ "arch:amd64" ]
  dependencies:
    - "build-kernel-amd64"
    - "build-kernel-arm64"
    - "build-shim-rust-amd64"
    - "build-shim-rust-arm64"
  variables:
    GIT_STRATEGY: none
  script:
    - aws s3 cp tools/packaging/kernel/vmlinux-amd64 s3://kata-containers-ci-artifacts/$CI_COMMIT_REF_NAME/amd64/vmlinux
    - aws s3 cp tools/packaging/kernel/vmlinux-arm64 s3://kata-containers-ci-artifacts/$CI_COMMIT_REF_NAME/arm64/vmlinux
    - aws s3 cp src/runtime-rs/containerd-shim-kata-v2-rust-amd64 s3://kata-containers-ci-artifacts/$CI_COMMIT_REF_NAME/amd64/containerd-shim-kata-v2
    - aws s3 cp src/runtime-rs/containerd-shim-kata-v2-rust-arm64 s3://kata-containers-ci-artifacts/$CI_COMMIT_REF_NAME/arm64/containerd-shim-kata-v2
    - echo $CI_COMMIT_REF_NAME > LATEST && aws s3 cp LATEST s3://kata-containers-ci-artifacts/LATEST
