#
# Copyright (c) 2021 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

gomod:
	 GO111MODULE=on go mod edit -replace=github.com/kata-containers/tests/metrics/exec=../exec
	 GO111MODULE=on go mod tidy
