# Copyright (c) 2024 NVIDIA Corporation
#
# SPDX-License-Identifier: Apache-2.0

FROM alpine:3.20.0

RUN apk update && apk --no-cache add gpg gpg-agent coreutils bash curl make \
 	gcc g++ pkgconf libselinux-dev gpg-agent
