#
# Copyright (c) 2018 SUSE
#
# SPDX-License-Identifier: Apache-2.0

ARG IMAGE_REGISTRY=docker.io
# NOTE: OS_VERSION is set according to config.sh
FROM ${IMAGE_REGISTRY}/debian:@OS_VERSION@

# RUN commands
RUN apt-get update && apt-get --no-install-recommends install -y \
    apt-utils \
    autoconf \
    automake \
    binutils \
    build-essential \
    ca-certificates \
    chrony \
    coreutils \
    curl \
    debianutils \
    debootstrap \
    g++ \
    gcc \
    git \
    libc-dev \
    libstdc++-6-dev \
    m4 \
    make \
    musl \
    musl-dev \
    musl-tools \
    sed \
    systemd \
    tar \
    vim \
    wget

# This will install the proper golang to build Kata components
@INSTALL_GO@
@INSTALL_RUST@
