// Copyright (c) 2019-2022 Alibaba Cloud
// Copyright (c) 2019-2022 Ant Group
//
// SPDX-License-Identifier: Apache-2.0
//

use dragonball::ThreadType;
use seccompiler::{BpfProgram, SeccompAction, SeccompFilter};
use std::convert::TryInto;

pub fn get_seccomp_filter(thread_type: &ThreadType) -> BpfProgram {
    let rules = match thread_type {
        ThreadType::All => get_process_seccomp_rules(),
        // Add rules for finer-grained restrictions as needed
        ThreadType::Vmm => vec![],
        ThreadType::Vcpu => vec![],
    };
    SeccompFilter::new(
        rules.into_iter().collect(),
        SeccompAction::Trap,
        SeccompAction::Allow,
        std::env::consts::ARCH.try_into().unwrap(),
    )
    .and_then(|f| f.try_into())
    .unwrap_or_default()
}

pub fn get_process_seccomp_rules() -> Vec<(i64, Vec<seccompiler::SeccompRule>)> {
    vec![
        (libc::SYS_read, vec![]),
        (libc::SYS_write, vec![]),
        (libc::SYS_open, vec![]),
        (libc::SYS_close, vec![]),
        (libc::SYS_stat, vec![]),
        (libc::SYS_fstat, vec![]),
        (libc::SYS_poll, vec![]),
        (libc::SYS_lseek, vec![]),
        (libc::SYS_mmap, vec![]),
        (libc::SYS_mprotect, vec![]),
        (libc::SYS_munmap, vec![]),
        (libc::SYS_brk, vec![]),
        (libc::SYS_rt_sigaction, vec![]),
        (libc::SYS_rt_sigprocmask, vec![]),
        (libc::SYS_rt_sigreturn, vec![]),
        (libc::SYS_ioctl, vec![]),
        (libc::SYS_pread64, vec![]),
        (libc::SYS_pwrite64, vec![]),
        (libc::SYS_readv, vec![]),
        (libc::SYS_writev, vec![]),
        (libc::SYS_access, vec![]),
        (libc::SYS_sched_yield, vec![]),
        (libc::SYS_mremap, vec![]),
        (libc::SYS_mincore, vec![]),
        (libc::SYS_madvise, vec![]),
        (libc::SYS_dup, vec![]),
        (libc::SYS_nanosleep, vec![]),
        (libc::SYS_getpid, vec![]),
        (libc::SYS_socket, vec![]),
        (libc::SYS_connect, vec![]),
        (libc::SYS_sendto, vec![]),
        (libc::SYS_recvfrom, vec![]),
        (libc::SYS_sendmsg, vec![]),
        (libc::SYS_recvmsg, vec![]),
        (libc::SYS_shutdown, vec![]),
        (libc::SYS_bind, vec![]),
        (libc::SYS_listen, vec![]),
        (libc::SYS_socketpair, vec![]),
        (libc::SYS_setsockopt, vec![]),
        (libc::SYS_getsockopt, vec![]),
        (libc::SYS_clone, vec![]),
        (libc::SYS_exit, vec![]),
        (libc::SYS_wait4, vec![]),
        (libc::SYS_kill, vec![]),
        (libc::SYS_fcntl, vec![]),
        (libc::SYS_fsync, vec![]),
        (libc::SYS_fdatasync, vec![]),
        (libc::SYS_ftruncate, vec![]),
        (libc::SYS_getcwd, vec![]),
        (libc::SYS_mkdir, vec![]),
        (libc::SYS_unlink, vec![]),
        (libc::SYS_readlink, vec![]),
        (libc::SYS_umask, vec![]),
        (libc::SYS_gettimeofday, vec![]),
        (libc::SYS_getuid, vec![]),
        (libc::SYS_getpgrp, vec![]),
        (libc::SYS_setsid, vec![]),
        (libc::SYS_getpgid, vec![]),
        (libc::SYS_sigaltstack, vec![]),
        (libc::SYS_statfs, vec![]),
        (libc::SYS_prctl, vec![]),
        (libc::SYS_mount, vec![]),
        (libc::SYS_gettid, vec![]),
        (libc::SYS_getxattr, vec![]),
        (libc::SYS_tkill, vec![]),
        (libc::SYS_futex, vec![]),
        (libc::SYS_sched_setaffinity, vec![]),
        (libc::SYS_sched_getaffinity, vec![]),
        (libc::SYS_io_setup, vec![]),
        (libc::SYS_io_destroy, vec![]),
        (libc::SYS_io_getevents, vec![]),
        (libc::SYS_io_submit, vec![]),
        (libc::SYS_io_cancel, vec![]),
        (libc::SYS_getdents64, vec![]),
        (libc::SYS_restart_syscall, vec![]),
        (libc::SYS_clock_gettime, vec![]),
        (libc::SYS_clock_nanosleep, vec![]),
        (libc::SYS_exit_group, vec![]),
        (libc::SYS_epoll_wait, vec![]),
        (libc::SYS_epoll_ctl, vec![]),
        (libc::SYS_tgkill, vec![]),
        (libc::SYS_mbind, vec![]),
        (libc::SYS_openat, vec![]),
        (libc::SYS_mkdirat, vec![]),
        (libc::SYS_newfstatat, vec![]),
        (libc::SYS_unlinkat, vec![]),
        (libc::SYS_readlinkat, vec![]),
        (libc::SYS_faccessat, vec![]),
        (libc::SYS_ppoll, vec![]),
        (libc::SYS_set_robust_list, vec![]),
        (libc::SYS_epoll_pwait, vec![]),
        (libc::SYS_timerfd_create, vec![]),
        (libc::SYS_fallocate, vec![]),
        (libc::SYS_timerfd_settime, vec![]),
        (libc::SYS_accept4, vec![]),
        (libc::SYS_eventfd2, vec![]),
        (libc::SYS_epoll_create1, vec![]),
        (libc::SYS_pipe2, vec![]),
        (libc::SYS_preadv, vec![]),
        (libc::SYS_pwritev, vec![]),
        (libc::SYS_prlimit64, vec![]),
        (libc::SYS_setns, vec![]),
        (libc::SYS_seccomp, vec![]),
        (libc::SYS_getrandom, vec![]),
        (libc::SYS_memfd_create, vec![]),
        (libc::SYS_statx, vec![]),
        (libc::SYS_rseq, vec![]),
        (libc::SYS_io_uring_setup, vec![]),
        (libc::SYS_io_uring_enter, vec![]),
        (libc::SYS_io_uring_register, vec![]),
        (libc::SYS_clone3, vec![]),
        (libc::SYS_close_range, vec![]),
        (libc::SYS_landlock_create_ruleset, vec![]),
        (libc::SYS_landlock_add_rule, vec![]),
        (libc::SYS_landlock_restrict_self, vec![]),
    ]
}
