// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: cdiresolver.proto
package cdiresolver

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type CDIResolverService interface {
	AllocatePodDevices(context.Context, *PodRequest) (*PhysicalDeviceResponse, error)
	AllocateContainerDevices(context.Context, *ContainerRequest) (*PhysicalDeviceResponse, error)
	FreeContainerDevices(context.Context, *ContainerRequest) (*PhysicalDeviceResponse, error)
	FreePodDevices(context.Context, *PodRequest) (*PhysicalDeviceResponse, error)
}

func RegisterCDIResolverService(srv *ttrpc.Server, svc CDIResolverService) {
	srv.RegisterService("cdiresolver.CDIResolver", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"AllocatePodDevices": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req PodRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.AllocatePodDevices(ctx, &req)
			},
			"AllocateContainerDevices": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ContainerRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.AllocateContainerDevices(ctx, &req)
			},
			"FreeContainerDevices": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ContainerRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.FreeContainerDevices(ctx, &req)
			},
			"FreePodDevices": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req PodRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.FreePodDevices(ctx, &req)
			},
		},
	})
}

type cdiresolverClient struct {
	client *ttrpc.Client
}

func NewCDIResolverClient(client *ttrpc.Client) CDIResolverService {
	return &cdiresolverClient{
		client: client,
	}
}

func (c *cdiresolverClient) AllocatePodDevices(ctx context.Context, req *PodRequest) (*PhysicalDeviceResponse, error) {
	var resp PhysicalDeviceResponse
	if err := c.client.Call(ctx, "cdiresolver.CDIResolver", "AllocatePodDevices", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *cdiresolverClient) AllocateContainerDevices(ctx context.Context, req *ContainerRequest) (*PhysicalDeviceResponse, error) {
	var resp PhysicalDeviceResponse
	if err := c.client.Call(ctx, "cdiresolver.CDIResolver", "AllocateContainerDevices", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *cdiresolverClient) FreeContainerDevices(ctx context.Context, req *ContainerRequest) (*PhysicalDeviceResponse, error) {
	var resp PhysicalDeviceResponse
	if err := c.client.Call(ctx, "cdiresolver.CDIResolver", "FreeContainerDevices", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *cdiresolverClient) FreePodDevices(ctx context.Context, req *PodRequest) (*PhysicalDeviceResponse, error) {
	var resp PhysicalDeviceResponse
	if err := c.client.Call(ctx, "cdiresolver.CDIResolver", "FreePodDevices", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
