#!/bin/bash
#
# Copyright (c) 2025 NVIDIA Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

set -e
set -o pipefail

kubernetes_dir=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091 # import based on variable
source "${kubernetes_dir}/../../common.bash"

# Enable NVRC trace logging for NVIDIA GPU runtime via drop-in config
enable_nvrc_trace() {
	local config_dir="/opt/kata/share/defaults/kata-containers/runtimes/${KATA_HYPERVISOR}/config.d"
	local drop_in_file="${config_dir}/90-nvrc-trace.toml"
	local kernel_params_drop_in="${config_dir}/30-kernel-params.toml"

	# Check if drop-in already exists
	if [[ -f "${drop_in_file}" ]]; then
		info "NVRC trace logging already enabled via drop-in: ${drop_in_file}"
		return 0
	fi

	# Read kernel_params from the existing 30-kernel-params.toml drop-in if it exists,
	# otherwise fall back to the base runtime config
	local base_params=""
	if [[ -f "${kernel_params_drop_in}" ]]; then
		base_params=$(grep -E '^kernel_params\s*=' "${kernel_params_drop_in}" | sed 's/^kernel_params\s*=\s*"\(.*\)"/\1/' || true)
	else
		local runtime_config="/opt/kata/share/defaults/kata-containers/runtimes/${KATA_HYPERVISOR}/configuration-${KATA_HYPERVISOR}.toml"
		if [[ -f "${runtime_config}" ]]; then
			base_params=$(grep -E '^kernel_params\s*=' "${runtime_config}" | sed 's/^kernel_params\s*=\s*"\(.*\)"/\1/' || true)
		fi
	fi

	# Add nvrc.log=trace to kernel params
	local new_params="${base_params} nvrc.log=trace"

	# Create drop-in file
	info "Creating NVRC trace drop-in: ${drop_in_file}"
	sudo mkdir -p "${config_dir}"
	sudo tee "${drop_in_file}" > /dev/null <<EOF
# NVRC trace logging for NVIDIA GPU tests
# Generated by run_kubernetes_nv_tests.sh

[hypervisor.qemu]
kernel_params = "${new_params}"
EOF
}

cleanup() {
	true
}

trap cleanup EXIT

# Setting to "yes" enables fail fast, stopping execution at the first failed test.
K8S_TEST_FAIL_FAST="${K8S_TEST_FAIL_FAST:-no}"

# Enable NVRC trace logging by default for NVIDIA GPU tests
ENABLE_NVRC_TRACE="${ENABLE_NVRC_TRACE:-true}"

if [[ -n "${K8S_TEST_NV:-}" ]]; then
	mapfile -d " " -t K8S_TEST_NV <<< "${K8S_TEST_NV}"
else
	K8S_TEST_NV=("k8s-confidential-attestation.bats" \
		"k8s-nvidia-cuda.bats" \
		"k8s-nvidia-nim.bats")
fi

SUPPORTED_HYPERVISORS=("qemu-nvidia-gpu" "qemu-nvidia-gpu-snp" "qemu-nvidia-gpu-tdx")
export KATA_HYPERVISOR="${KATA_HYPERVISOR:-qemu-nvidia-gpu}"
# shellcheck disable=SC2076 # intentionally use literal string matching
if [[ ! " ${SUPPORTED_HYPERVISORS[*]} " =~ " ${KATA_HYPERVISOR} " ]]; then
	die "Unsupported KATA_HYPERVISOR=${KATA_HYPERVISOR}. Must be one of: ${SUPPORTED_HYPERVISORS[*]}"
fi

ensure_yq

if [[ "${ENABLE_NVRC_TRACE:-true}" == "true" ]]; then
	enable_nvrc_trace
fi

# Use common bats test runner with proper reporting
export BATS_TEST_FAIL_FAST="${K8S_TEST_FAIL_FAST}"
run_bats_tests "${kubernetes_dir}" K8S_TEST_NV
