[package]
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
name = "service"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
containerd-shim = { workspace = true }
containerd-shim-protos = { features = ["async", "sandbox"], workspace = true }
slog = { workspace = true }
slog-scope = { workspace = true }
tokio = { features = ["rt-multi-thread"], workspace = true }
ttrpc = { workspace = true }

# Local dependencies
common = { workspace = true }
kata-types = { workspace = true }
logging = { workspace = true }
runtimes = { workspace = true }


[package.metadata.cargo-machete]
ignored = ["slog-scope"]
