#
# Copyright (c) 2019 SUSE LLC
#
# SPDX-License-Identifier: Apache-2.0

from opensuse/tumbleweed

RUN zypper --non-interactive refresh; \
    zypper --non-interactive install --no-recommends --force-resolution cpio curl dracut gcc git-core make tar; \
    zypper --non-interactive clean --all;


# This will install the proper golang to build Kata components
@INSTALL_GO@
