[package]
authors = ["The Kata Containers community <kata-dev@lists.katacontainers.io>"]
description = "Constants and data types shared by Kata Containers components"
edition = "2018"
homepage = "https://katacontainers.io/"
keywords = ["container", "kata", "runtime"]
license = "Apache-2.0"
name = "kata-types"
readme = "README.md"
repository = "https://github.com/kata-containers/kata-containers.git"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
base64 = { workspace = true }
bitmask-enum = "2.1.0"
byte-unit = "5.2.3"
crc = "3.4.0"
devicemapper = { optional = true, workspace = true }
flate2 = "1.1"
glob = "0.3.0"
gpt = "4.1.0"
lazy_static = "1.4.0"
nix = { workspace = true }
num_cpus = "1.13.1"
oci-spec = { workspace = true }
regex = "1.10.5"
safe-path = { optional = true, path = "../safe-path" }
scopeguard = "1.0.0"
serde = { features = ["derive"], version = "1.0.100" }
serde-enum-str = "0.5"
serde_json = "1.0.73"
sha2 = { workspace = true }
slog = "2.5.2"
slog-scope = "4.4.0"
sysinfo = { workspace = true }
thiserror = { workspace = true }
tokio = { features = ["rt", "time"], optional = true, workspace = true }
toml = { workspace = true }
[target.'cfg(target_os = "macos")'.dependencies]
sysctl = "0.7.1"

[dev-dependencies]
nix = { workspace = true }
rstest = { workspace = true }
tempfile = "3.19.1"
test-utils = { path = "../test-utils" }

[features]
default = []
devicemapper = ["dep:devicemapper", "dep:tokio"]
enable-vendor = []
safe-path = ["dep:safe-path"]                    # safe-path is platform-specific
