# Copyright (c) 2019 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Usage: FROM [image name]
FROM @OS_DISTRIBUTION@

ARG TEST_REPO="https://github.com/kata-containers/tests"

RUN @UPDATE@

RUN @DEPENDENCIES@

# Install packages
RUN cd "/home/" && git clone "${TEST_REPO}"
RUN cd "/home/tests" && ./cmd/kata-manager/kata-manager.sh install-packages
RUN kata-runtime kata-env

CMD ["/bin/bash"]
