[package]
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
name = "virt_container"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
awaitgroup = { workspace = true }
containerd-shim-protos = { workspace = true }
libc = { workspace = true }
nix = { workspace = true }
oci-spec = { workspace = true }
protobuf = { workspace = true }
sendfd = { features = ["tokio"], version = "0.4.3" }
serde = { features = ["derive"], workspace = true }
serde_json = { workspace = true }
slog = { workspace = true }
slog-scope = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { features = ["v4"], version = "1" }

# Local dependencies
agent = { workspace = true }
common = { workspace = true }
hypervisor = { features = ["cloud-hypervisor"], workspace = true }
kata-sys-util = { workspace = true }
kata-types = { workspace = true }
logging = { workspace = true }
persist = { workspace = true }
pod-resources-rs = { workspace = true }
resource = { workspace = true }
runtime-spec = { workspace = true }

[features]
default = ["cloud-hypervisor"]

# Enable the Cloud Hypervisor driver
cloud-hypervisor = ["hypervisor/cloud-hypervisor"]

# Enable the build-in VMM Dragtonball
dragonball = ["hypervisor/dragonball"]

# Enable the OpenVMM driver
openvmm = ["hypervisor/openvmm"]

[package.metadata.cargo-machete]
ignored = ["slog-scope"]
