[package]
authors = ["The Kata Containers community <kata-dev@lists.katacontainers.io>"]
description = "A secure sandbox for Kata Containers"
edition = "2018"
homepage = "https://katacontainers.io/"
keywords = ["dragonball", "kata-containers", "sandbox", "vmm"]
license = "Apache-2.0"
name = "dragonball"
repository = "https://github.com/kata-containers/kata-containers.git"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
arc-swap = { workspace = true }
bytes = { workspace = true }
crossbeam-channel = { workspace = true }
dbs-acpi = { workspace = true }
dbs-address-space = { workspace = true }
dbs-allocator = { workspace = true }
dbs-arch = { workspace = true }
dbs-boot = { workspace = true }
dbs-device = { workspace = true }
dbs-interrupt = { features = ["kvm-irq", "split-irq"], workspace = true }
dbs-legacy-devices = { workspace = true }
dbs-pci = { optional = true, workspace = true }
dbs-snapshot = { workspace = true }
dbs-upcall = { optional = true, workspace = true }
dbs-utils = { workspace = true }
dbs-virtio-devices = { features = [
  "virtio-mmio",
], optional = true, workspace = true }
derivative = { workspace = true }
kata-sys-util = { workspace = true }
kvm-bindings = { features = ["fam-wrappers", "serde"], workspace = true }
kvm-ioctls = { workspace = true }
lazy_static = { workspace = true }
libc = { workspace = true }
linux-loader = { workspace = true }
log = { workspace = true }
nix = { features = ["mman"], workspace = true }
procfs = { workspace = true }
prometheus = { features = ["process"], workspace = true }
seccompiler = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
slog = { workspace = true }
slog-scope = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
vfio-bindings = { optional = true, workspace = true }
vfio-ioctls = { optional = true, workspace = true }
virtio-queue = { optional = true, workspace = true }
vm-memory = { features = ["backend-mmap"], workspace = true }
vmm-sys-util = { features = ["with-serde"], workspace = true }

[target.'cfg(target_arch = "x86_64")'.dependencies]
tdx = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
slog-async = { workspace = true }
slog-term = { workspace = true }
test-utils = { workspace = true }

[features]
acpi = []
atomic-guest-memory = ["vm-memory/backend-atomic"]
hotplug = ["virtio-vsock"]
virtio-blk = ["dbs-virtio-devices/virtio-blk", "virtio-queue"]
virtio-net = ["dbs-virtio-devices/virtio-net", "virtio-queue"]
virtio-vsock = ["dbs-virtio-devices/virtio-vsock", "virtio-queue"]
# virtio-fs only work on atomic-guest-memory
host-device = ["dep:dbs-pci", "dep:vfio-bindings", "dep:vfio-ioctls"]
vhost-net = ["dbs-virtio-devices/vhost-net"]
vhost-user-blk = ["dbs-virtio-devices/vhost-user-blk"]
vhost-user-fs = ["dbs-virtio-devices/vhost-user-fs"]
vhost-user-net = ["dbs-virtio-devices/vhost-user-net"]
virtio-balloon = ["dbs-virtio-devices/virtio-balloon", "virtio-queue"]
virtio-fs = [
  "atomic-guest-memory",
  "dbs-virtio-devices/virtio-fs-pro",
  "virtio-queue",
]
virtio-mem = [
  "atomic-guest-memory",
  "dbs-virtio-devices/virtio-mem",
  "virtio-queue",
]
virtio-rng = ["dbs-virtio-devices/virtio-rng", "virtio-queue"]

[lints.rust]
unexpected_cfgs = { check-cfg = [
  'cfg(feature, values("test-mock"))',
], level = "warn" }

[package.metadata.cargo-machete]
ignored = ["vfio-bindings"]
