# Copyright (c) 2023 Microsoft Corporation
#
# SPDX-License-Identifier: Apache-2.0

ARG IMAGE_REGISTRY=mcr.microsoft.com
FROM ${IMAGE_REGISTRY}/azurelinux/base/core:@OS_VERSION@

RUN tdnf -y install \
    ca-certificates \
    build-essential \
    dnf \
    git \
    tar \
    xz \
    # TODO: Remove when this issue is fixed:
    # https://github.com/microsoft/azurelinux/issues/13971
    --exclude=aznfs

@INSTALL_RUST@
