/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * API version: 0.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// VhostUserConfig struct for VhostUserConfig
type VhostUserConfig struct {
	Sock string `json:"sock"`
	NumQueues int32 `json:"num_queues"`
	Queuesize int32 `json:"queue:size,omitempty"`
}
