#
# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

From fedora:27

RUN dnf -y update && dnf install -y git systemd pkgconfig gcc coreutils

# This will install the proper golang to build Kata components
@INSTALL_GO@
