# Copyright (c) 2020 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "kata-trace-forwarder"
version = "0.0.1"

[dependencies]
anyhow.workspace = true
bincode = "1.3.3"
byteorder = "1.4.3"
clap = { features = ["cargo"], workspace = true }
futures.workspace = true
libc.workspace = true
nix = { features = ["fs", "user"], version = "0.30.1" }
opentelemetry = { features = ["trace"], version = "0.32.0" }
opentelemetry-otlp = { features = ["grpc-tonic", "trace"], version = "0.32.0" }
opentelemetry_sdk = { features = ["rt-tokio"], version = "0.32.1" }
tokio = { features = ["rt-multi-thread"], version = "1" }
vsock = "0.2.3"

# Note: this crate sets the slog 'max_*' features which allows the log level
# to be modified at runtime.
logging.workspace = true
slog.workspace = true

privdrop = "0.5.1"
