#
# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

ARG IMAGE_REGISTRY=docker.io
FROM ${IMAGE_REGISTRY}/fedora:30

@SET_PROXY@

RUN dnf -y update && dnf install -y \
    autoconf \
    automake \
    bash \
    binutils \
    chrony \
    clang \
    coreutils \
    curl \
    gcc \
    gcc-c++ \
    git \
    glibc-common \
    glibc-devel \
    glibc-headers \
    glibc-static \
    glibc-utils \
    libstdc++-devel \
    libstdc++-static \
    m4 \
    make \
    musl-gcc \
    pkgconfig \
    sed \
    systemd \
    tar \
    vim \
    which && \
    dnf clean all

# This will install the proper packages to build Kata components
@INSTALL_RUST@
