// Copyright (c) 2019-2023 Alibaba Cloud
// Copyright (c) 2019-2023 Ant Group
//
// SPDX-License-Identifier: Apache-2.0
//

use std::{collections::HashMap, sync::Arc};

use anyhow::{anyhow, Context, Ok, Result};
use kata_sys_util::rand::RandomBytes;
use tokio::sync::Mutex;

use crate::{
    BlockConfig, DeviceConfig, Hypervisor, KATA_BLK_DEV_TYPE, KATA_MMIO_BLK_DEV_TYPE,
    VIRTIO_BLOCK_MMIO, VIRTIO_BLOCK_PCI,
};

use super::{
    util::{get_host_path, get_virt_drive_name},
    Device,
};
pub type ArcMutexBoxDevice = Arc<Mutex<dyn Device>>;

/// block_index and released_block_index are used to search an available block index
/// in Sandbox.
///
/// @block_index generally default is 1 for <vdb>;
/// @released_block_index for blk devices removed and indexes will released at the same time.
#[derive(Clone, Debug, Default)]
struct SharedInfo {
    block_index: u64,
    released_block_index: Vec<u64>,
}

impl SharedInfo {
    fn new() -> Self {
        SharedInfo {
            block_index: 1,
            released_block_index: vec![],
        }
    }

    // declare the available block index
    fn declare_device_index(&mut self) -> Result<u64> {
        let current_index = if let Some(index) = self.released_block_index.pop() {
            index
        } else {
            self.block_index
        };
        self.block_index += 1;

        Ok(current_index)
    }

    fn release_device_index(&mut self, index: u64) {
        self.released_block_index.push(index);
        self.released_block_index.sort_by(|a, b| b.cmp(a));
    }
}

// Device manager will manage the lifecycle of sandbox device
pub struct DeviceManager {
    devices: HashMap<String, ArcMutexBoxDevice>,
    hypervisor: Arc<dyn Hypervisor>,
    shared_info: SharedInfo,
}

impl DeviceManager {
    pub async fn new(hypervisor: Arc<dyn Hypervisor>) -> Result<Self> {
        let devices = HashMap::<String, ArcMutexBoxDevice>::new();
        Ok(DeviceManager {
            devices,
            hypervisor,
            shared_info: SharedInfo::new(),
        })
    }

    pub async fn new_device(&mut self, device_config: DeviceConfig) -> Result<String> {
        let device_id = if let Some(dev) = self.find_device(&device_config).await {
            dev
        } else {
            self.create_device(&device_config)
                .await
                .context("failed to create device")?
        };
        Ok(device_id)
    }

    pub async fn try_add_device(&mut self, device_id: String) -> Result<()> {
        // get device
        let device = self
            .devices
            .get(&device_id)
            .context("failed to find device")?;
        // attach device
        let result = device.lock().await.attach(self.hypervisor.as_ref()).await;
        // handle attach error
        if let Err(e) = result {
            if let DeviceConfig::Block(config) = device.lock().await.get_device_info().await {
                self.shared_info.release_device_index(config.index);
            };
            self.devices.remove(&device_id);
            return Err(e);
        }
        Ok(())
    }

    async fn find_device(&self, device_config: &DeviceConfig) -> Option<String> {
        for (device_id, dev) in &self.devices {
            match dev.lock().await.get_device_info().await {
                DeviceConfig::Block(config) => match device_config {
                    DeviceConfig::Block(ref config_new) => {
                        if config_new.path_on_host == config.path_on_host {
                            return Some(device_id.to_string());
                        }
                    }
                    _ => {
                        continue;
                    }
                },
                _ => {
                    // TODO: support find other device type
                    continue;
                }
            }
        }
        None
    }

    async fn create_device(&mut self, device_config: &DeviceConfig) -> Result<String> {
        // device ID must be generated by manager instead of device itself
        // in case of ID collision
        let device_id = self.new_device_id()?;
        let dev: ArcMutexBoxDevice = match device_config {
            DeviceConfig::Block(config) => self
                .create_block_device(config, device_id.clone())
                .await
                .context("failed to create device")?,
            _ => {
                return Err(anyhow!("invliad device type"));
            }
        };
        // register device to devices
        self.devices.insert(device_id.clone(), dev.clone());
        Ok(device_id)
    }

    async fn create_block_device(
        &mut self,
        config: &BlockConfig,
        device_id: String,
    ) -> Result<ArcMutexBoxDevice> {
        let mut block_config = config.clone();
        block_config.id = device_id.clone();
        // get hypervisor block driver
        let block_driver = match self
            .hypervisor
            .hypervisor_config()
            .await
            .blockdev_info
            .block_device_driver
            .as_str()
        {
            // convert the block driver to kata type
            VIRTIO_BLOCK_MMIO => KATA_MMIO_BLK_DEV_TYPE.to_string(),
            VIRTIO_BLOCK_PCI => KATA_BLK_DEV_TYPE.to_string(),
            _ => "".to_string(),
        };
        block_config.driver_option = block_driver;
        // generate virt path
        let current_index = self.shared_info.declare_device_index()?;
        block_config.index = current_index;
        let drive_name = get_virt_drive_name(current_index as i32)?;
        block_config.virt_path = format!("/dev/{}", drive_name);
        // if the path on host is empty, we need to get device host path from major and minor
        // Otherwise, it might be rawfile based block device
        if block_config.path_on_host.is_empty() {
            block_config.path_on_host = get_host_path("b".to_owned(), config.major, config.minor)
                .context("failed to get host path")?;
        }
        Ok(Arc::new(Mutex::new(BlockConfig::new(block_config))))
    }

    // device ID must be generated by device manager instead of device itself
    // in case of ID collision
    fn new_device_id(&self) -> Result<String> {
        for _ in 0..5 {
            let rand_bytes = RandomBytes::new(8);
            let id = format!("{:x}", rand_bytes);

            // check collision in devices
            if self.devices.get(&id).is_none() {
                return Ok(id);
            }
        }

        Err(anyhow!("ID are exhausted"))
    }
}
