#
# Copyright (c) 2019 SUSE LLC
#
# SPDX-License-Identifier: Apache-2.0

# openSUSE Tumbleweed image has only 'latest' tag so ignore DL3006 rule.
# hadolint ignore=DL3006
FROM opensuse/tumbleweed

# zypper -y or --non-interactive can be used interchangeably here so ignore
# DL3034 rule.
# hadolint ignore=DL3034
RUN zypper --non-interactive refresh; \
    zypper --non-interactive install --no-recommends --force-resolution \
    autoconf \
    automake \
    binutils \
    coreutils \
    cpio \
    curl \
    dracut \
    gcc \
    gcc-c++ \
    git-core \
    glibc-devel \
    glibc-devel-static \
    glibc-utils \
    libstdc++-devel \
    linux-glibc-devel \
    m4 \
    make \
    sed \
    tar \
    vim \
    which; \
    zypper --non-interactive clean --all;


@INSTALL_RUST@
