[package]
authors = ["Alibaba Dragonball Team"]
description = "dbs-pci is a crate for emulating pci device"
edition = "2018"
homepage = "https://github.com/openanolis/dragonball-sandbox"
keywords = ["devices", "dragonball", "pci", "secure-sandbox"]
license = "Apache-2.0"
name = "dbs-pci"
readme = "README.md"
repository = "https://github.com/openanolis/dragonball-sandbox/tree/main/crates/dbs-pci"
version = "0.1.0"

[dependencies]
byteorder = "1.4.3"
dbs-address-space = { workspace = true }
dbs-allocator = { workspace = true }
dbs-boot = { workspace = true }
dbs-device = { workspace = true }
dbs-interrupt = { features = [
  "kvm-irq",
  "kvm-legacy-irq",
  "kvm-msi-irq",
], workspace = true }
dbs-virtio-devices = { workspace = true }
log = "0.4.14"
serde = "1.0.27"
thiserror = { workspace = true }

dbs-utils = { workspace = true }
kvm-bindings = { workspace = true }
kvm-ioctls = { workspace = true }
libc = "0.2.39"
vfio-bindings = { workspace = true }
vfio-ioctls = { workspace = true }
virtio-queue = { workspace = true }
vm-memory = { workspace = true }


[dev-dependencies]
dbs-arch = { workspace = true }
kvm-ioctls = { workspace = true }
nix = { workspace = true }
test-utils = { workspace = true }

[lints.rust]
unexpected_cfgs = { check-cfg = [
  'cfg(feature, values("test-mock"))',
], level = "warn" }
