[package]
authors = ["Alibaba Dragonball Team"]
description = "Virtio device backend driver framework and device drivers"
edition = "2018"
homepage = "https://github.com/openanolis/dragonball-sandbox"
keywords = ["devices", "dragonball", "secure-sandbox", "virtio"]
license = "Apache-2.0 AND BSD-3-Clause"
name = "dbs-virtio-devices"
readme = "README.md"
repository = "https://github.com/openanolis/dragonball-sandbox/tree/main/crates/dbs-virtio-devices"
version = "0.3.1"

[dependencies]
byteorder = "1.4.3"
caps = "0.5.3"
dbs-address-space = { workspace = true }
dbs-boot = { workspace = true }
dbs-device = { workspace = true }
dbs-interrupt = { features = [
  "kvm-legacy-irq",
  "kvm-msi-irq",
  "split-legacy-irq",
], workspace = true }
dbs-snapshot = { workspace = true }
dbs-utils = { workspace = true }
epoll = ">=4.3.1, <4.3.2"
fuse-backend-rs = { optional = true, version = "0.14.0" }
io-uring = "0.5.2"
kata-sys-util = { workspace = true }
kvm-bindings = { workspace = true }
kvm-ioctls = { workspace = true }
libc = "0.2.119"
log = "0.4.14"
nix = { workspace = true }
nydus-api = "0.4.1"
nydus-rafs = "0.4.1"
nydus-storage = "0.7.2"
rlimit = "0.7.0"
sendfd = "0.4.3"
serde = { features = ["derive"], version = "1.0.27" }
serde_json = "1.0.9"
thiserror = { workspace = true }
threadpool = "1"
timerfd = "1.0"
vhost-rs = { optional = true, package = "vhost", version = "0.15.0" }
virtio-bindings = { workspace = true }
virtio-queue = { workspace = true }
vm-memory = { features = ["backend-mmap"], workspace = true }
vmm-sys-util = { workspace = true }

[dev-dependencies]
test-utils = { workspace = true }
vm-memory = { features = ["backend-atomic", "backend-mmap"], workspace = true }

[features]
test-resources = []
vhost = ["vhost-rs/vhost-kern", "vhost-rs/vhost-user-frontend", "virtio-mmio"]
vhost-net = ["vhost", "vhost-rs/vhost-net"]
vhost-user = ["vhost"]
vhost-user-blk = ["vhost-user"]
vhost-user-fs = ["vhost-user"]
vhost-user-net = ["vhost-user"]
virtio-balloon = ["virtio-mmio"]
virtio-blk = ["virtio-mmio"]
virtio-fs = ["fuse-backend-rs/virtiofs", "nydus-rafs/virtio-fs", "virtio-mmio"]
virtio-fs-pro = [
  "nydus-storage/backend-oss",
  "nydus-storage/backend-registry",
  "virtio-fs",
]
virtio-mem = ["virtio-mmio"]
virtio-mmio = []
virtio-net = ["virtio-mmio"]
virtio-vsock = ["virtio-mmio"]
