# Netkit virtual devices — used by system probe for eBPF-based network visibility
CONFIG_NETKIT=y

# vhost vsock — guest-side of the virtio socket device, needed for system probe
# communication inside the microVM
CONFIG_VHOST_VSOCK=y

# emissary dummy interface
CONFIG_DUMMY=y
