#
# Copyright (c) 2018  Yash Jain
#
# SPDX-License-Identifier: Apache-2.0

#ubuntu: docker image to be used to create a rootfs
#@OS_VERSION@: Docker image version to build this dockerfile
from ubuntu:@OS_VERSION@

# This dockerfile needs to provide all the componets need to build a rootfs
# Install any package need to create a rootfs (package manager, extra tools)

# RUN commands
RUN apt-get update && apt-get install -y curl wget systemd debootstrap git build-essential
# This will install the proper golang to build Kata components
@INSTALL_GO@

