[package]
authors = ["James O. D. Hunt <james.o.hunt@intel.com>"]
edition.workspace = true
license.workspace = true
name = "vsock-exporter"
version = "0.1.0"

[dependencies]
async-trait.workspace = true
byteorder = "1.4.3"
libc.workspace = true
opentelemetry = { features = ["serialize"], workspace = true }
serde_json = "1.0"
slog = { features = [
  "dynamic-keys",
  "max_level_trace",
  "release_max_level_debug",
], workspace = true }
thiserror.workspace = true
tokio.workspace = true
tokio-vsock.workspace = true
