#
# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

From fedora:@OS_VERSION@

@SET_PROXY@

RUN dnf -y update && dnf install -y \
chrony \
curl \
gcc \
git \
libseccomp \
libseccomp-devel \
make \
pkgconfig \
redhat-release \
systemd

# This will install the proper golang to build Kata components
@INSTALL_GO@
