#
# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

From fedora:@OS_VERSION@

@SET_PROXY@

RUN dnf -y update && dnf install -y git redhat-release systemd pkgconfig gcc coreutils

# This will install the proper golang to build Kata components
@INSTALL_GO@
