#
# Copyright (c) 2018 HyperHQ Inc.
#
# SPDX-License-Identifier: Apache-2.0

ARG IMAGE_REGISTRY=docker.io
FROM ${IMAGE_REGISTRY}/alpine:3.15

RUN apk update && apk add --no-cache \
    apk-tools-static \
    autoconf \
    automake \
    bash \
    binutils \
    cmake \
    coreutils \
    curl \
    g++ \
    gcc \
    git \
    libc-dev \
    linux-headers \
    m4 \
    make \
    musl \
    musl-dev \
    protoc \
    tar \
    xz
# aarch64 requires this name -- link for all
RUN ln -s /usr/bin/gcc "/usr/bin/$(uname -m)-linux-musl-gcc"
