#
# Copyright (c) 2018 HyperHQ Inc.
#
# SPDX-License-Identifier: Apache-2.0

ARG IMAGE_REGISTRY=docker.io
FROM ${IMAGE_REGISTRY}/alpine:3.13

RUN apk update && apk add \
    apk-tools-static \
    autoconf \
    automake \
    bash \
    binutils \
    cmake \
    coreutils \
    curl \
    g++ \
    gcc \
    git \
    libc-dev \
    libseccomp \
    libseccomp-dev \
    linux-headers \
    m4 \
    make \
    musl \
    musl-dev \
    tar
