# https://lukasgeiter.github.io/mkdocs-awesome-nav/
nav:
  - Home:
    - index.md
    - Getting Started:
      - prerequisites.md
      - installation.md
    - Configuration:
        - Helm: helm-configuration.md
        - Runtime: runtime-configuration.md
        - Annotations: pod-annotations.md
  - Platform Support:
    - hypervisors.md
  - Guides:
    - Use Cases:
      - NVIDIA GPU Passthrough: use-cases/NVIDIA-GPU-passthrough-and-Kata-QEMU.md
      - NVIDIA vGPU: use-cases/NVIDIA-GPU-passthrough-and-Kata.md
      - Intel Discrete GPU: use-cases/Intel-Discrete-GPU-passthrough-and-Kata.md
    - Contributing:
      - Documentation: doc-contributing.md
  - Misc:
    - Architecture: design/architecture/
