# Copyright (c) 2020 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

default: build

build:
	RUSTFLAGS="--deny warnings" cargo build -v

clean:
	cargo clean

vendor:
	cargo vendor

test:

install:

check:

.PHONY: \
	build \
	test \
	check \
	install \
	clean \
	vendor
