name: Cargo Deny Check

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cargo-deny:
    name: cargo-deny
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        checks:
          # Note: advisories checks are currently covered in OSV-scanner instead
          - bans licenses sources
    steps:
      - name: Checkout the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run the cargo deny check ( ${{ matrix.checks }})
        uses: EmbarkStudios/cargo-deny-action@3fd3802e88374d3fe9159b834c7714ec57d6c979 #2.0.15
        with:
          command: check ${{ matrix.checks }}
