name: Kata Containers CoCo Stability Tests Weekly
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  kata-containers-ci-on-push:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: ./.github/workflows/ci-weekly.yaml
    with:
      commit-hash: ${{ github.sha }}
      pr-number: "weekly"
      tag: ${{ github.sha }}-weekly
      target-branch: ${{ github.ref_name }}
    secrets:
      authenticated_image_user: ${{ secrets.AUTHENTICATED_IMAGE_USER }}
      authenticated_image_password: ${{ secrets.AUTHENTICATED_IMAGE_PASSWORD }}
      az_appid: ${{ secrets.AZ_APPID }}
      az_password: ${{ secrets.AZ_PASSWORD }}
      az_tenant_id: ${{ secrets.AZ_TENANT_ID }}
      az_subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      quay_deployer_username: ${{ secrets.QUAY_DEPLOYER_USERNAME }}
      quay_deployer_password: ${{ secrets.QUAY_DEPLOYER_PASSWORD }}
