name: Kata Containers CI (manually triggered)
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  kata-containers-ci-on-push:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: ./.github/workflows/ci.yaml
    with:
      commit-hash: ${{ github.sha }}
      pr-number: "dev"
      tag: ${{ github.sha }}-dev
      target-branch: ${{ github.ref_name }}

    secrets:
      authenticated_image_user: ${{ secrets.AUTHENTICATED_IMAGE_USER }}
      authenticated_image_password: ${{ secrets.AUTHENTICATED_IMAGE_PASSWORD }}
      az_appid: ${{ secrets.AZ_APPID }}
      az_password: ${{ secrets.AZ_PASSWORD }}
      az_tenant_id: ${{ secrets.AZ_TENANT_ID }}
      az_subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      ci_hkd_path: ${{ secrets.CI_HKD_PATH }}
      ita_key: ${{ secrets.ITA_KEY }}
      quay_deployer_username: ${{ secrets.QUAY_DEPLOYER_USERNAME }}
      quay_deployer_password: ${{ secrets.QUAY_DEPLOYER_PASSWORD }}

  build-checks:
    uses: ./.github/workflows/build-checks.yaml
    with:
      instance: ubuntu-22.04
