name: Kata Containers CI (manually triggered)
on:
  workflow_dispatch:
    inputs:
      registry:
        description: "Registry to push the kata-deploy image to"
        required: false
        type: string
        default: ghcr.io
      repo:
        description: "Repository to push the kata-deploy image to; defaults to <owner>/kata-deploy-ci"
        required: false
        type: string
        default: ""
      tag:
        description: "Tag to push the kata-deploy image under; defaults to <sha>-dev"
        required: false
        type: string
        default: ""

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-devel
  cancel-in-progress: true

permissions: {}

jobs:
  build-kata-static-tarball-amd64:
    permissions:
      contents: read
      packages: write # needed to push build artifacts to ghcr.io
      id-token: write # needed to sign images and generate attestations
      attestations: write # needed to generate artifact attestations
    uses: ./.github/workflows/build-kata-static-tarball-amd64.yaml
    with:
      tarball-suffix: -${{ inputs.tag || format('{0}-dev', github.sha) }}
      commit-hash: ${{ github.sha }}
      target-branch: ${{ github.ref_name }}
    secrets:
      KBUILD_SIGN_PIN: ${{ secrets.KBUILD_SIGN_PIN }}

  publish-kata-deploy-image-amd64:
    needs: build-kata-static-tarball-amd64
    permissions:
      contents: read
      packages: write # needed to push build artifacts to ghcr.io
    uses: ./.github/workflows/publish-kata-images.yaml
    with:
      tarball-suffix: -${{ inputs.tag || format('{0}-dev', github.sha) }}
      registry: ${{ inputs.registry }}
      repo: ${{ inputs.repo || format('{0}/kata-deploy-ci', github.repository_owner) }}
      tag: ${{ inputs.tag || format('{0}-dev', github.sha) }}-amd64
      commit-hash: ${{ github.sha }}
      target-branch: ${{ github.ref_name }}
      runner: ubuntu-22.04
      arch: amd64
    secrets:
      QUAY_DEPLOYER_PASSWORD: ${{ secrets.QUAY_DEPLOYER_PASSWORD }}
