name: Run Kata Containers CI - ppc64le Only
on:
  workflow_call:
    inputs:
      commit-hash:
        required: true
        type: string
      pr-number:
        required: true
        type: string
      tag:
        required: true
        type: string
      target-branch:
        required: false
        type: string
        default: ""
      skip-test:
        required: false
        type: string
        default: no
    secrets:
      AUTHENTICATED_IMAGE_PASSWORD:
        required: false
      AZ_APPID:
        required: false
      AZ_TENANT_ID:
        required: false
      AZ_SUBSCRIPTION_ID:
        required: false
      CI_HKD_PATH:
        required: false
      ITA_KEY:
        required: false
      QUAY_DEPLOYER_PASSWORD:
        required: true
      NGC_API_KEY:
        required: false
      KBUILD_SIGN_PIN:
        required: false

permissions: {}

jobs:
  build-kata-static-tarball-ppc64le:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-kata-static-tarball-ppc64le.yaml
    with:
      tarball-suffix: -${{ inputs.tag }}
      commit-hash: ${{ inputs.commit-hash }}
      target-branch: ${{ inputs.target-branch }}
    secrets:
      QUAY_DEPLOYER_PASSWORD: ${{ secrets.QUAY_DEPLOYER_PASSWORD }}

  publish-kata-deploy-payload-ppc64le:
    needs: build-kata-static-tarball-ppc64le
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/publish-kata-images.yaml
    with:
      tarball-suffix: -${{ inputs.tag }}
      registry: ghcr.io
      repo: ${{ github.repository_owner }}/kata-deploy-ci
      tag: ${{ inputs.tag }}-ppc64le
      commit-hash: ${{ inputs.commit-hash }}
      target-branch: ${{ inputs.target-branch }}
      runner: ubuntu-24.04-ppc64le
      arch: ppc64le
    secrets:
      QUAY_DEPLOYER_PASSWORD: ${{ secrets.QUAY_DEPLOYER_PASSWORD }}

  run-k8s-tests-on-ppc64le:
    if: ${{ inputs.skip-test != 'yes' }}
    needs: publish-kata-deploy-payload-ppc64le
    uses: ./.github/workflows/run-k8s-tests-on-ppc64le.yaml
    with:
      registry: ghcr.io
      repo: ${{ github.repository_owner }}/kata-deploy-ci
      tag: ${{ inputs.tag }}-ppc64le
      commit-hash: ${{ inputs.commit-hash }}
      pr-number: ${{ inputs.pr-number }}
      target-branch: ${{ inputs.target-branch }}

  # Phase 2: Containerd tests (disabled for Phase 1)
  # Uncomment this job when ready to test containerd (creates/destroys clusters)
  # run-cri-containerd-tests-ppc64le:
  #   if: ${{ inputs.skip-test != 'yes' }}
  #   needs: build-kata-static-tarball-ppc64le
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       params: [
  #         { containerd_version: active, vmm: qemu },
  #         { containerd_version: active, vmm: qemu-runtime-rs },
  #       ]
  #   uses: ./.github/workflows/run-cri-containerd-tests.yaml
  #   with:
  #     tarball-suffix: -${{ inputs.tag }}
  #     commit-hash: ${{ inputs.commit-hash }}
  #     target-branch: ${{ inputs.target-branch }}
  #     runner: ppc64le-small
  #     arch: ppc64le
  #     containerd_version: ${{ matrix.params.containerd_version }}
  #     vmm: ${{ matrix.params.vmm }}

