on:
  schedule:
    - cron:  '0 23 * * 0'
  workflow_dispatch:

permissions: {}

name: Docs URL Alive Check
jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    # don't run this action on forks
    if: github.repository_owner == 'kata-containers'
    env:
      target_branch: ${{ github.base_ref }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit

    - name: Set env
      run: |
        echo "GOPATH=${GITHUB_WORKSPACE}" >> "$GITHUB_ENV"
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Install yq
      run: |
        ./ci/install_yq.sh
      env:
        INSTALL_IN_GOPATH: false

    - name: Read properties from versions.yaml
      run: |
        go_version="$(yq '.languages.golang.version' versions.yaml)"
        [ -n "$go_version" ]
        echo "GO_VERSION=${go_version}" >> "$GITHUB_ENV"

    - name: Setup Golang version ${{ env.GO_VERSION }}
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Docs URL Alive Check
      run: |
        make docs-url-alive-check
