/*
Cloud Hypervisor API

Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// TimeoutStrategy The strategy to apply when the migration timeout is reached. Cancel will abort the migration and keep the VM running on the source. Ignore will proceed with the migration regardless of the downtime requirement.
type TimeoutStrategy string

// List of TimeoutStrategy
const (
	CANCEL TimeoutStrategy = "Cancel"
	IGNORE TimeoutStrategy = "Ignore"
)

// All allowed values of TimeoutStrategy enum
var AllowedTimeoutStrategyEnumValues = []TimeoutStrategy{
	"Cancel",
	"Ignore",
}

func (v *TimeoutStrategy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TimeoutStrategy(value)
	for _, existing := range AllowedTimeoutStrategyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TimeoutStrategy", value)
}

// NewTimeoutStrategyFromValue returns a pointer to a valid TimeoutStrategy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTimeoutStrategyFromValue(v string) (*TimeoutStrategy, error) {
	ev := TimeoutStrategy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TimeoutStrategy: valid values are %v", v, AllowedTimeoutStrategyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TimeoutStrategy) IsValid() bool {
	for _, existing := range AllowedTimeoutStrategyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TimeoutStrategy value
func (v TimeoutStrategy) Ptr() *TimeoutStrategy {
	return &v
}

type NullableTimeoutStrategy struct {
	value *TimeoutStrategy
	isSet bool
}

func (v NullableTimeoutStrategy) Get() *TimeoutStrategy {
	return v.value
}

func (v *NullableTimeoutStrategy) Set(val *TimeoutStrategy) {
	v.value = val
	v.isSet = true
}

func (v NullableTimeoutStrategy) IsSet() bool {
	return v.isSet
}

func (v *NullableTimeoutStrategy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimeoutStrategy(val *TimeoutStrategy) *NullableTimeoutStrategy {
	return &NullableTimeoutStrategy{value: val, isSet: true}
}

func (v NullableTimeoutStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimeoutStrategy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
