/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * API version: 0.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SgxEpcConfig struct for SgxEpcConfig
type SgxEpcConfig struct {
	Size     int64 `json:"size"`
	Prefault bool  `json:"prefault,omitempty"`
}
