/*
Cloud Hypervisor API

Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GenericVhostUserConfig struct for GenericVhostUserConfig
type GenericVhostUserConfig struct {
	Socket      string  `json:"socket"`
	QueueSizes  []int32 `json:"queue_sizes"`
	PciSegment  *int32  `json:"pci_segment,omitempty"`
	PciDeviceId *int32  `json:"pci_device_id,omitempty"`
	DeviceType  int32   `json:"device_type"`
}

// NewGenericVhostUserConfig instantiates a new GenericVhostUserConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenericVhostUserConfig(socket string, queueSizes []int32, deviceType int32) *GenericVhostUserConfig {
	this := GenericVhostUserConfig{}
	this.Socket = socket
	this.QueueSizes = queueSizes
	this.DeviceType = deviceType
	return &this
}

// NewGenericVhostUserConfigWithDefaults instantiates a new GenericVhostUserConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenericVhostUserConfigWithDefaults() *GenericVhostUserConfig {
	this := GenericVhostUserConfig{}
	return &this
}

// GetSocket returns the Socket field value
func (o *GenericVhostUserConfig) GetSocket() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Socket
}

// GetSocketOk returns a tuple with the Socket field value
// and a boolean to check if the value has been set.
func (o *GenericVhostUserConfig) GetSocketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Socket, true
}

// SetSocket sets field value
func (o *GenericVhostUserConfig) SetSocket(v string) {
	o.Socket = v
}

// GetQueueSizes returns the QueueSizes field value
func (o *GenericVhostUserConfig) GetQueueSizes() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.QueueSizes
}

// GetQueueSizesOk returns a tuple with the QueueSizes field value
// and a boolean to check if the value has been set.
func (o *GenericVhostUserConfig) GetQueueSizesOk() (*[]int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QueueSizes, true
}

// SetQueueSizes sets field value
func (o *GenericVhostUserConfig) SetQueueSizes(v []int32) {
	o.QueueSizes = v
}

// GetPciSegment returns the PciSegment field value if set, zero value otherwise.
func (o *GenericVhostUserConfig) GetPciSegment() int32 {
	if o == nil || o.PciSegment == nil {
		var ret int32
		return ret
	}
	return *o.PciSegment
}

// GetPciSegmentOk returns a tuple with the PciSegment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenericVhostUserConfig) GetPciSegmentOk() (*int32, bool) {
	if o == nil || o.PciSegment == nil {
		return nil, false
	}
	return o.PciSegment, true
}

// HasPciSegment returns a boolean if a field has been set.
func (o *GenericVhostUserConfig) HasPciSegment() bool {
	if o != nil && o.PciSegment != nil {
		return true
	}

	return false
}

// SetPciSegment gets a reference to the given int32 and assigns it to the PciSegment field.
func (o *GenericVhostUserConfig) SetPciSegment(v int32) {
	o.PciSegment = &v
}

// GetPciDeviceId returns the PciDeviceId field value if set, zero value otherwise.
func (o *GenericVhostUserConfig) GetPciDeviceId() int32 {
	if o == nil || o.PciDeviceId == nil {
		var ret int32
		return ret
	}
	return *o.PciDeviceId
}

// GetPciDeviceIdOk returns a tuple with the PciDeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenericVhostUserConfig) GetPciDeviceIdOk() (*int32, bool) {
	if o == nil || o.PciDeviceId == nil {
		return nil, false
	}
	return o.PciDeviceId, true
}

// HasPciDeviceId returns a boolean if a field has been set.
func (o *GenericVhostUserConfig) HasPciDeviceId() bool {
	if o != nil && o.PciDeviceId != nil {
		return true
	}

	return false
}

// SetPciDeviceId gets a reference to the given int32 and assigns it to the PciDeviceId field.
func (o *GenericVhostUserConfig) SetPciDeviceId(v int32) {
	o.PciDeviceId = &v
}

// GetDeviceType returns the DeviceType field value
func (o *GenericVhostUserConfig) GetDeviceType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DeviceType
}

// GetDeviceTypeOk returns a tuple with the DeviceType field value
// and a boolean to check if the value has been set.
func (o *GenericVhostUserConfig) GetDeviceTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceType, true
}

// SetDeviceType sets field value
func (o *GenericVhostUserConfig) SetDeviceType(v int32) {
	o.DeviceType = v
}

func (o GenericVhostUserConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["socket"] = o.Socket
	}
	if true {
		toSerialize["queue_sizes"] = o.QueueSizes
	}
	if o.PciSegment != nil {
		toSerialize["pci_segment"] = o.PciSegment
	}
	if o.PciDeviceId != nil {
		toSerialize["pci_device_id"] = o.PciDeviceId
	}
	if true {
		toSerialize["device_type"] = o.DeviceType
	}
	return json.Marshal(toSerialize)
}

type NullableGenericVhostUserConfig struct {
	value *GenericVhostUserConfig
	isSet bool
}

func (v NullableGenericVhostUserConfig) Get() *GenericVhostUserConfig {
	return v.value
}

func (v *NullableGenericVhostUserConfig) Set(val *GenericVhostUserConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableGenericVhostUserConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableGenericVhostUserConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenericVhostUserConfig(val *GenericVhostUserConfig) *NullableGenericVhostUserConfig {
	return &NullableGenericVhostUserConfig{value: val, isSet: true}
}

func (v NullableGenericVhostUserConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenericVhostUserConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
