/*
Cloud Hypervisor API

Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// MigrationMode Memory transfer mode. Precopy transfers all guest memory before the destination resumes. Postcopy resumes the destination first and faults guest pages in on demand.
type MigrationMode string

// List of MigrationMode
const (
	PRECOPY  MigrationMode = "Precopy"
	POSTCOPY MigrationMode = "Postcopy"
)

// All allowed values of MigrationMode enum
var AllowedMigrationModeEnumValues = []MigrationMode{
	"Precopy",
	"Postcopy",
}

func (v *MigrationMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := MigrationMode(value)
	for _, existing := range AllowedMigrationModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid MigrationMode", value)
}

// NewMigrationModeFromValue returns a pointer to a valid MigrationMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewMigrationModeFromValue(v string) (*MigrationMode, error) {
	ev := MigrationMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for MigrationMode: valid values are %v", v, AllowedMigrationModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v MigrationMode) IsValid() bool {
	for _, existing := range AllowedMigrationModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to MigrationMode value
func (v MigrationMode) Ptr() *MigrationMode {
	return &v
}

type NullableMigrationMode struct {
	value *MigrationMode
	isSet bool
}

func (v NullableMigrationMode) Get() *MigrationMode {
	return v.value
}

func (v *NullableMigrationMode) Set(val *MigrationMode) {
	v.value = val
	v.isSet = true
}

func (v NullableMigrationMode) IsSet() bool {
	return v.isSet
}

func (v *NullableMigrationMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMigrationMode(val *MigrationMode) *NullableMigrationMode {
	return &NullableMigrationMode{value: val, isSet: true}
}

func (v NullableMigrationMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMigrationMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
