/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * API version: 0.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// VsockConfig struct for VsockConfig
type VsockConfig struct {
	// Guest Vsock CID
	Cid int64 `json:"cid"`
	// Path to UNIX domain socket, used to proxy vsock connections.
	Socket string `json:"socket"`
	Iommu  bool   `json:"iommu,omitempty"`
	Id     string `json:"id,omitempty"`
}
