/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * API version: 0.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// DeviceNode struct for DeviceNode
type DeviceNode struct {
	Id        string                   `json:"id,omitempty"`
	Resources []map[string]interface{} `json:"resources,omitempty"`
	Children  []string                 `json:"children,omitempty"`
	PciBdf    int32                    `json:"pci_bdf,omitempty"`
}
